"""Writes THIRD_PARTY_NOTICES.md: every third-party component the project ships, with its licence, from the
dependency trees as they are installed (not a hand-kept list).

- The browser app: the npm packages it depends on at run time (apps/web, `npm ls --omit=dev`), the Rust
  crates compiled into the core's WASM (`cargo tree -p circuit-core-wasm`), and ngspice.wasm.
- The server: the Python packages the API and the simulation worker need, the Rust crates in the core's
  Python module, and the native ngspice.

    .venv/Scripts/python tools/licenses/third_party.py          # after changing a dependency
    .venv/Scripts/python tools/licenses/third_party.py --check  # exit 1 when the file is out of date
"""

from __future__ import annotations

import importlib.metadata as md
import json
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
OUT = REPO / "THIRD_PARTY_NOTICES.md"
OURS = {"circuit-core", "circuit-core-wasm", "circuit-core-py", "tutor-api", "sim-runner", "@tutor/web", "@tutor/core"}


def npm_packages() -> list[tuple[str, str, str]]:
    out = subprocess.run("npm ls --omit=dev --all --json", cwd=REPO / "apps/web", capture_output=True, text=True,
                         shell=True, check=False).stdout
    found: dict[tuple[str, str], str] = {}

    def walk(deps: dict) -> None:
        for name, d in (deps or {}).items():
            if name in OURS or "version" not in d:
                continue
            pkg = REPO / "apps/web/node_modules" / name / "package.json"
            lic = json.loads(pkg.read_text(encoding="utf-8")).get("license", "see package") if pkg.exists() else "?"
            found[(name, d["version"])] = lic if isinstance(lic, str) else lic.get("type", "?")
            walk(d.get("dependencies"))

    walk(json.loads(out).get("dependencies"))
    return sorted((n, v, lic) for (n, v), lic in found.items())


def crates(package: str, target: str | None) -> list[tuple[str, str, str]]:
    cmd = ["cargo", "tree", "-p", package, "-e", "normal", "--prefix", "none", "-f", "{p}\t{l}"]
    if target:
        cmd += ["--target", target]
    lines = subprocess.run(cmd, cwd=REPO, capture_output=True, text=True, check=True).stdout.splitlines()
    found = set()
    for line in lines:
        spec, _, lic = line.partition("\t")
        name, version = spec.split()[:2]
        if name not in OURS:
            found.add((name, version.lstrip("v"), lic.replace("(*)", "").strip() or "?"))
    return sorted(found)


def python_packages(roots: tuple[str, ...]) -> list[tuple[str, str, str]]:
    seen: dict[str, tuple[str, str, str]] = {}
    todo = list(roots)
    while todo:
        name = todo.pop()
        key = re.sub(r"[-_.]+", "-", name).lower()
        if key in seen:
            continue
        try:
            dist = md.distribution(name)
        except md.PackageNotFoundError:
            continue
        m = dist.metadata
        lic = m.get("License-Expression") or ""
        if not lic:
            classifiers = [c.split(" :: ")[-1] for c in m.get_all("Classifier") or [] if c.startswith("License ::")]
            lic = ", ".join(classifiers) or (m.get("License") or "?").splitlines()[0][:60]
        seen[key] = (m["Name"], dist.version, lic)
        for req in dist.requires or []:
            if "extra ==" in req:
                continue
            todo.append(re.split(r"[\s;<>=!~\[(]", req, maxsplit=1)[0])
    return sorted(v for k, v in seen.items() if v[0] not in OURS)


def table(rows: list[tuple[str, str, str]]) -> list[str]:
    return ["| Component | Version | Licence |", "| --- | --- | --- |"] + [f"| {n} | {v} | {lic} |" for n, v, lic in rows]


def render() -> str:
    ngspice_version = next(line.split("=", 1)[1].strip().strip('"')
                           for line in (REPO / "third_party/ngspice/pin.env").read_text(encoding="utf-8").splitlines()
                           if line.startswith("NGSPICE_VERSION="))
    out = [
        "# Third-party notices",
        "",
        "Analog-Copilot is licensed under the PolyForm Noncommercial License 1.0.0 (LICENSE.md). That licence covers",
        "the project's own code only. The components below keep their own licences; their licence texts ship with",
        "each package (node_modules, the crates' sources, the Python distributions) and are part of these notices.",
        "",
        "Generated by `tools/licenses/third_party.py` from the installed dependency trees; do not edit by hand.",
        "",
        "## ngspice",
        "",
        f"ngspice {ngspice_version} (third_party/ngspice), built from the pinned upstream source plus `patches/`:",
        "`ngspice.wasm` in the browser and the native binary in the simulation worker. ngspice is under its",
        "\"Modified BSD\" licence except for listed parts (its `COPYING`, shipped next to `ngspice.wasm`). Two",
        "of those are in our builds: `src/maths/sparse` (MIT-style) and `src/frontend/numparam` (LGPL 2.0 or",
        "later). ngspice is shipped as a separate file, loaded at run time, so it can be replaced; its",
        "corresponding source is the pinned tarball and `third_party/ngspice/patches`.",
        "",
        "## In the browser app",
        "",
        "npm packages (apps/web, run-time dependencies and theirs):",
        "",
        *table(npm_packages()),
        "",
        "elkjs is offered under EPL-2.0 or GPL-3.0-or-later; Analog-Copilot uses it under EPL-2.0, unmodified.",
        "",
        "Rust crates compiled into the core's WebAssembly (`circuit-core-wasm`):",
        "",
        *table(crates("circuit-core-wasm", "wasm32-unknown-unknown")),
        "",
        "## On the server",
        "",
        "Python packages of the API and the simulation worker, and theirs:",
        "",
        *table(python_packages(("tutor-api", "sim-runner"))),
        "",
        "Rust crates compiled into the core's Python module (`circuit-core-py`):",
        "",
        *table(crates("circuit-core-py", None)),
        "",
    ]
    return "\n".join(out)


if __name__ == "__main__":
    text = render()
    if "--check" in sys.argv:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            sys.exit(f"{OUT.name} is out of date: run tools/licenses/third_party.py")
        print(f"{OUT.name} is up to date")
    else:
        OUT.write_text(text, encoding="utf-8", newline="\n")
        print(f"wrote {OUT.name}")
